#!/bin/bash

argv=("$@")

export FERMI_DIR=/opt/pulsar/stow/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.19-0/x86_64-unknown-linux-gnu-libc2.19-0

. $FERMI_DIR/fermi-init.sh

"${argv[@]}"
